name: tests
on:
  push:
    branches-ignore:
      - deploy
    tags-ignore:
      - "*"

concurrency:
  group: paddle-integration-firestore-tests

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Git checkout
      uses: actions/checkout@master

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci

    - name: test
      run: ./test.sh
      env:
        NODE_ENV: ci

    - name: install playwright deps
      run: npx playwright install

    - name: test-e2e
      run: ./test-e2e.sh
      env:
        NODE_ENV: e2e
        AUTH_CODE: ${{ secrets.AUTH_CODE }}
        VENDOR_ID: ${{ secrets.VENDOR_ID }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}